export default {
    ['--body-bgcolor']: '#252525',
    ['--light-bgcolor']: '#2e2e2e',

    ['--font-color']: '#b1b1b1',
    ['--font-color-shallow']: '#6f6f6f',
    ['--font-color-white']: '#dcdde4',
    ['--font-color-grey']: '#5C5C5C',
    ['--font-color-grey2']: '#808080',
    ['--font-color-grey-shallow']: '#727272',
    ['--border']: '#3F3F3F',
    ['--scrollbar-color']: '#3a3a3a',
    ['--round-hover-bgcolor']: '#373737',
    ['--stripe-bg']: '#323232',
    ['--shallow-theme-bgcolor']: '#2D2625',
    ['--shallow-theme-bgcolor-hover']: '#352726',
    // header
    ['--header-bgcolor']: '#252525',
    ['--header-font-color']: '#b1b1b1',
    ['--header-input-color']: '#b1b1b1',
    ['--header-input-bgcolor']: '#4B4B4B',
    ['--header-input-placeholder-color']: '#727272',
    // menu
    ['--menu-item-hover-bgcolor']: '#1d1d1d',
    ['--menu-bgcolor']: '#202020',
    ['--menu-item-active-bgcolor']: '#1b1b1b',
    // player
    ['--player-bgcolor']: '#252525',
    // playlist
    ['--playlist-bgcolor']: '#363636',
    ['--playlist-hover-bgcolor']: '#2e2e2e',
    // search
    ['--search-bgcolor']: '#363636',
    // progress
    ['--progress-bgcolor']: '#232323',
    // prompt
    ['--prompt-bg-color']: '#363636',
    // button
    ['--button-border-color']: '#454545',
    ['--button-hover-bgcolor']: '#3E3E3E',
    // input
    ['--input-color']: '#b1b1b1',
    ['--input-bgcolor']: '#4b4b4b',
    // tab
    ['--tab-item-color']: '#797979',
    ['--tab-item-hover-color']: '#b4b4b4',
    ['--tab-item-active-color']: '#fff',
    // song-detail
    ['--song-shallow-grey-bgcolor']: '#2a2a2a',
    // modal
    ['--modal-bg-color']: '#202020',
}